import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import Provider from "@/components/common/Provider";
import Header from "@/components/header/Header";

const pretendard = localFont({
    src: "./fonts/Pretendard-Regular.woff2",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout = ({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) => {
    return (
        <html lang="ko">
            <body className={`${pretendard.className} w-5/6 mx-auto 2xl:w-3/6`}>
                <Provider attribute="class" defaultTheme="system" enableSystem>
                    <Header />
                    {children}
                </Provider>
            </body>
        </html>
    );
};

export default RootLayout;
